[package]
name = "unge-tauri-host"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
unge-interaction = { path = "../../crates/unge-interaction" }
tauri-runtime-wry = "=2.11.4"
unge-core = { path = "../../crates/unge-core" }
unge-executor = { path = "../../crates/unge-executor" }
unge-render = { path = "../../crates/unge-render" }
unge-tauri = { path = "../../crates/unge-tauri", features = ["acx"] }
unge-acx = { path = "../../crates/unge-acx" }
tauri = { version = "=2.11.6", features = ["unstable"] }
pollster = "0.4"
[build-dependencies]
tauri-build = { version = "2", features = [] }
