export type Locale = 'en' | 'ja' | 'zh-CN';
export const messages = {
  en: { missing_group: 'This group no longer exists.', group_exists: 'A group with this ID already exists.', invalid_group_label: 'Enter a name of 1–256 characters.', execution_busy: "Another execution is active.", unknown_run: "This execution is no longer retained.", execution_unavailable: "Execution is not configured.", invalid_graph: "The graph cannot be executed.", document_mismatch: "This execution belongs to another document.", execution_failed: "Execution failed.", execution_panicked: "A host error interrupted execution.", execution_aborted: "Execution was abandoned before starting.", invalid_pointer: 'The pointer position is invalid.', pointer_busy: 'Another pointer is editing this view.', invalid_connection: 'These ports cannot be connected.', revision_conflict: 'The document changed. Refresh before editing again.', invalid_command: 'This edit is invalid.', invalid_properties: 'A property value is invalid or missing.', unknown_view: 'This window is not registered.', limit_exceeded: 'This request exceeds the supported limit.', state_unavailable: 'The document is unavailable.', missing_node: 'This node no longer exists.', invalid_selection: 'The selection is invalid.', renderer_unavailable: 'The renderer is unavailable.', gpu_error: 'Rendering failed.', worker_error: 'The operation failed.', invalid_request: 'The request is invalid.', invalid_node: 'Node metadata is invalid.' },
  ja: { missing_group: 'このグループは存在しません。', group_exists: '同じIDのグループが存在します。', invalid_group_label: '名前を1〜256文字で入力してください。', execution_busy: "別の実行が進行中です。", unknown_run: "この実行の記録は保持されていません。", execution_unavailable: "実行サービスが設定されていません。", invalid_graph: "このグラフは実行できません。", document_mismatch: "別のドキュメントの実行です。", execution_failed: "実行に失敗しました。", execution_panicked: "ホストのエラーで実行が中断しました。", execution_aborted: "開始前に実行が破棄されました。", invalid_pointer: 'ポインターの座標が無効です。', pointer_busy: 'この画面は別のポインターで操作中です。', invalid_connection: 'このポート同士は接続できません。', revision_conflict: 'ドキュメントが更新されました。再読み込みしてから編集してください。', invalid_command: 'この編集は無効です。', invalid_properties: 'プロパティの値が無効、または必須項目が未入力です。', unknown_view: 'このウインドウは登録されていません。', limit_exceeded: 'リクエストが上限を超えています。', state_unavailable: 'ドキュメントを利用できません。', missing_node: 'このノードは存在しません。', invalid_selection: '選択が無効です。', renderer_unavailable: 'レンダラーを利用できません。', gpu_error: '描画に失敗しました。', worker_error: '処理に失敗しました。', invalid_request: 'リクエストが無効です。', invalid_node: 'ノード情報が無効です。' },
  'zh-CN': { missing_group: '此组已不存在。', group_exists: '此ID的组已存在。', invalid_group_label: '请输入1〜256个字符的名称。', execution_busy: "另一个执行正在进行。", unknown_run: "此执行记录已不再保留。", execution_unavailable: "尚未配置执行服务。", invalid_graph: "此图无法执行。", document_mismatch: "此执行属于另一个文档。", execution_failed: "执行失败。", execution_panicked: "主机错误导致执行中断。", execution_aborted: "执行在开始前被放弃。", invalid_pointer: '指针位置无效。', pointer_busy: '另一个指针正在操作此视图。', invalid_connection: '这些端口无法连接。', revision_conflict: '文档已更新，请刷新后再编辑。', invalid_command: '此编辑无效。', invalid_properties: '属性值无效或缺少必填项。', unknown_view: '此窗口尚未注册。', limit_exceeded: '请求超出限制。', state_unavailable: '文档不可用。', missing_node: '此节点已不存在。', invalid_selection: '选择无效。', renderer_unavailable: '渲染器不可用。', gpu_error: '渲染失败。', worker_error: '操作失败。', invalid_request: '请求无效。', invalid_node: '节点信息无效。' },
} as const;
export function errorMessage(locale: Locale, code: string): string {
  const table: Record<string, string> = messages[locale];
  return table[code] ?? code;
}
